<?php
/**
 * @author Archigos
 * @copyright 2012
 * Originally based on the "Addon" to Maraschino by 'hernandito'
 * Please do not edit this file, edit 'settings.ini' instead
 */

require 'includes/required/errorreporting.php';
require 'includes/required/defaults.php';
require 'includes/required/langpack.php';
require 'includes/required/header_ipad.php';
require 'includes/required/jsoncommands.php';
?>

<!-- Left Menu: Start -->
<!-- Auto-Size Fix: DIV required for 'fixing' iFrame auto-size -->
<!-- Since this page is written with the iPad in mind (or any non-Retina 1024x768 device)
		The "Left Menu" should be restricted to 7 items. More information included in the
		documentation. -->
<div id="leftofframe">
<div id="nav">
    <?php writeAppFull($CallMara,Maraschino); ?>
</div>
<div id="nav">
    <?php writeAppFull($CallSab,SabNZBd); ?>
</div>
<div id="nav">
    <?php writeAppFull($CallSick,SickBeard); ?>
</div>
<div id="nav">
    <?php writeAppFull($CallCouch,CouchPotato); ?>
</div>
<div id="nav">
    <?php writeAppFull($CallXBMC,XBMC); ?>
</div>
<div id="nav">
    <?php writeAppFull($CalluTor,uTorrent); ?>
</div>
<div id="nav">
    <a class="classname2" target="myiframe" href="http://<?php echo $CallXBMC ?>"><img src="includes/images/apps/default.png" /></a>
</div>
</div>
<!-- Left Menu: End -->

<!-- Top Navigation: Start -->
<div id="navi" class="navi">
    <ul>
        <li><?php callRemote($iPad); ?></li>
        <li><?php writeAppURL($CallMara,Maraschino); ?></li>
        <li><?php writeAppURL($CallSab,SabNZBd); ?></li>
        <li><?php writeAppURL($CalluTor,'&micro;Torrent'); ?></li>
        <li><?php writeAppURL($CallSick,SickBeard); ?></li>
        <li><?php writeAppURL($CallCouch,CouchPotato); ?></li>
        <li><?php writeAppURL($CalliPad,Matrix); ?>
            <ul>
                <li><a href="http://<?php echo $ini['matrix_link'] ?>category=Movies" target="myiframe" title="Movies"><img src="includes/images/movies.png" width="104" height="104" /></a></li>
                <li><a href="http://<?php echo $ini['matrix_link'] ?>category=TV" target="myiframe" title="TV"><img src="includes/images/tv.png" width="104" height="104" /></a></li>
                <li><a href="http://<?php echo $ini['matrix_link'] ?>category=Apps" target="myiframe" title="Applications"><img src="includes/images/apps.png" width="104" height="104" /></a></li>
                <li><a href="http://<?php echo $ini['matrix_link'] ?>cat=14" target="myiframe" title="Xbox"><img src="includes/images/xbox.png" width="104" height="104" /></a></li>
            </ul>
        </li>
        <li><?php writeAppURL($CalliPad,NZB.su); ?>
            <ul>
                <li><a href="http://nzb.su" target="myiframe" title="NZB.su"><img src="includes/images/nzbsu.png" width="104" height="104" /></a></li>
                <li><a href="http://nzb.su/movies" target="myiframe" title="NZB.su Movies"><img src="includes/images/nzbsum.png" width="104" height="104" /></a></li>
                <li><a href="http://nzb.su/browse?t=5000" target="myiframe" title="NZB.su TV"><img src="includes/images/nzbsut.png" width="104" height="104" /></a></li>
            </ul>
        </li>
        <li><?php writeAppURL($CalliPad,Forums); ?>
            <ul>
                <li><a href="http://forum.xbmc.org/index.php" target="myiframe"><img src="includes/images/xbmc.png" width="140" height="50" /></a></li>
                <li><a href="http://openelec.tv/forum/recent" target="myiframe"><img src="includes/images/openelec.png" width="140" height="50" /></a></li>
                <li><a href="http://lime-technology.com/forum/index.php" target="myiframe"><img src="includes/images/unraid.png" width="140" height="50" /></a></li>
                <li><a href="http://forums.maraschinoproject.com/index.php" target="myiframe"><img src="includes/images/maraschino.png" width="140" height="50" /></a></li>
            </ul>
        </li>
        <li><?php writeAppURL($CalliPad,dBases); ?>
            <ul>
                <li><a href="http://www.imdb.com/" target="myiframe">IMDB</a></li>
                <li><a href="http://www.themoviedb.org/" target="myiframe">TheMovieDB</a></li>
                <li><a href="http://thetvdb.com/" target="myiframe">TheTVDB</a></li>
                <li><a href="http://www.joblo.com/blu-rays-dvds/release-dates/?" target="myiframe">DVD Releases</a></li>
                <li><a href="http://www.movieweb.com/movies/2012" target="myiframe">2012 Movies</a></li>
                <li><a href="http://www.rlslog.net/category/movies/hdrip/" target="myiframe">RlsLog.net</a></li>
                <li><a href="http://www.rottentomatoes.com/news/" target="myiframe">Rotten Tomatoes</a></li>
            </ul>
        </li>
        <li><?php writeAppURL($CalliPad,Favorites); ?>
            <ul> 
                <li><a href="http://www.engadget.com/" target="myiframe"><img src="includes/images/engadget.png" width="104" height="60" /></a></li> 
                <li><a href="http://blog.lifehacker.com/" target="myiframe"><img src="includes/images/lifehacker.png" width="104" height="60" /></a></li> 
                <li><a href="http://your demonoid link here" target="myiframe"><img src="includes/images/demonoid.png" width="104" height="60" /></a></li> 
                <li><a href="http://www.warez-bb.org/" target="myiframe"><img src="includes/images/warezbb.png" width="104" height="60" /></a></li> 
                <li><a href="http://www.cnn.com/" target="myiframe"><img src="includes/images/cnn.png" width="104" height="60" /></a></li>
                <li><a href="http://www.trakt.tv/" target="myiframe"><img src="includes/images/trakt.png" width="104" height="60" /></a></li>
                <li><a href="http://www.youtube.com/" target="myiframe"><img src="includes/images/youtube.png" width="104" height="60" /></a></li>
            </ul> 
        </li>
    </ul>
</div>
<!-- Top Navigation: End -->
<?php require 'includes\required\jsonframe.php'; ?>
<?php require 'includes\required\padframe.php'; ?>
</body>
</html>