<?php
/**
 * @author Archigos
 * @copyright 2012
 * @version 1.3 
 * Originally based on the "Addon" to Maraschino by 'hernandito'
 * Please do not edit this file, edit 'settings.ini' instead
 */

require 'includes/required/errorreporting.php';
require 'includes/required/defaults.php';
require 'includes/required/langpack.php';
require 'includes/required/jsoncommands.php';
?>
<link rel="stylesheet" type="text/css" href="includes/css/portal.css" />

<div id="nav"><strong>X </strong>
	<?php echo $JSONStart ?>XBMC.TakeScreenshot">Screenshot</a>
    <?php echo $JSONStart ?>XBMC.PlayerControl(Play)">Pause</a>
    <?php echo $JSONStart ?>XBMC.Action(ShowSubtitles)">Subtitles</a>
</div>
<div id="nav"><strong>Volume </strong>
    <?php echo $JSONStart ?>XBMC.Mute">Mute</a>
    <?php echo $JSONStart ?>XBMC.Action(VolumeUp)">&uparrow;</a>
    <?php echo $JSONStart ?>XBMC.Action(VolumeDown)">&downarrow;</a>
    <?php echo $JSONStart ?>XBMC.SetVolume(100%,showvolumebar)">Max</a>
</div>

<!-- Haven't found the correct code for these yet
<div id="nav"><strong>Watched </strong>
    <?php echo $JSONStart ?>XBMC.Action(SetWatched)">(un)Mark</a>
    <?php echo $JSONStart ?>XBMC.">Toggle</a>
</div>
-->

<div id="nav"><strong>Video </strong>
    <?php echo $JSONStart ?>XBMC.UpdateLibrary(video)">Update</a>
    <?php echo $JSONStart ?>XBMC.CleanLibrary(video)">Clean</a>
    <?php echo $JSONStart ?>XBMC.Reboot">Reboot</a> 
</div>
<div id="nav"><strong>Music </strong>
    <?php echo $JSONStart ?>XBMC.UpdateLibrary(music)">Update</a>
    <?php echo $JSONStart ?>XBMC.CleanLibrary(music)">Clean</a>
</div>
<div id="nav">
	<a class="classname2" href="includes/required/feed2js/build.php">RSS Editor</a>
</div>

</body>
</html>