<?php
/**
 * @author Archigos
 * @copyright 2012
 * @version 1.3 
 * Originally based on the "Addon" to Maraschino by 'hernandito'
 * Please do not edit this file, edit 'settings.ini' instead
 */

require 'includes/required/errorreporting.php';
require 'includes/required/defaults.php';
require 'includes/required/langpack.php';
require 'includes/required/header.php';
?>
<link href="includes/css/remote.css" rel="stylesheet" type="text/css">
<p style="color:white">Well, I know this page looks like crap... for now, I'm just screwing around with a layout... the Editor link is the only thing working.<br /><br />
Speaking of Editor link... I'll explain that more later, but for now, use it and the output you get should be placed in your 'settings.ini' in one of the five "feedX" variables.</p>
<a class="classname2" href="includes/required/feed2js/build.php">RSS Editor</a><br />

<div class="remotearrows">
	
</div>




<table align="right" border="0" cellpadding="0" cellspacing="0" draggable="false" height="108px" width="162px">
	<tr>
    	<td></td>
    	<td valign="baseline"><img src='includes/images/remote/up.png' border="0" /> </td>
    	<td></td>
    </tr>
	<tr>
    	<td><img src='includes/images/remote/left.png' border="0" /> </td>
    	<td><img src='includes/images/remote/down.png' border="0" /> </td>
    	<td><img src='includes/images/remote/right.png' border="0" /> </td>
    </tr>
</table> 
</body>
</html>